"""Entity rules for CoinGecko market-cap ranks 11-20 (config/entities.yaml).

The headlines were written or adapted while drafting and red-teaming the
rules on 2026-09-30. Some follow the wording of real headlines, quoted briefly
and without the article text; the rest are synthetic. Figures in them are
inputs for the matcher, not market data (market figures belong in research/).
Every positive must match its entity and every negative must not. Positives the
drafters dropped on purpose (recall given up for precision) are not listed
here; the residual risks are noted with the rules.

Matching runs on the same text the pipeline uses: title and excerpt joined by a
space, so some cases append an excerpt to the title.
"""

from __future__ import annotations

import pytest

from collector.config import load_entities
from collector.market.jobs import load_market_config
from collector.matching import match_text

from .conftest import ROOT

CASES: dict[str, dict[str, list[str]]] = {
    # HYPE
    "hyperliquid": {
        "pos": [
            "SEC Approves Listing of Grayscale Hyperliquid Staking ETF Under Generic Listing Standards",
            "Bitwise Launches Spot Hyperliquid ETF (BHYP) on NYSE With In-House Staking",
            "21Shares HYPE ETF records $4.9 million net inflows in first week of trading",
            "Hyperliquid Policy Center urges SEC, CFTC to harmonize rules for perpetual contracts",
            "HYPE Jumps 10% As NYSE Owner Highlights Hyperliquid's Wall Street Potential",
            "ICE CEO Jeff Sprecher says the decentralized exchange has grown bigger than Nasdaq Hyperliquid, with 11 people",
            "Native Markets' USDH stablecoin, with reserves managed by BlackRock and Bridge, goes live on HyperEVM",
            "USDH issuer Native Markets says BlackRock will manage off-chain reserves in Treasuries and cash",
            "Hyperion DeFi (Nasdaq: HYPD) to use its HYPE holdings as options collateral",
            "Hyperion DeFi adds HYPE to corporate treasury, now holds 1.86 million tokens",
            "PURR jumps 15% as Hyperliquid Strategies updates $1.9 billion HYPE treasury",
            "Trump says CFTC working to onshore Hyperliquid",
            "Hyper Foundation seeds Washington policy nonprofit with one million tokens",
            "Grayscale HYPE Trust files Form S-1/A with the SEC",
            "Bitwise's HYPE ETF to route sponsor fees into token buybacks",
            "$HYPE rallies after Intercontinental Exchange comments on onchain derivatives",
            "Hyperliquid treasury firm raises $300 million to buy tokens for its balance sheet",
            "Circle deploys native USDC on HyperCore, linking spot and perps order books",
            "Hyperliquid Assets Under Management in U.S. ETFs Top $1 Billion as HYPE staking yields draw investors",
            "DTCC: Tokenized collateral and perpetual futures on Hyperliquid",
            "Hyperliquid Labs submits comment letter to SEC on onchain perpetual futures",
            "Bitwise Hyperliquid ETF (BHYP) begins trading on NYSE Arca",
            "21Shares Hyperliquid ETF (THYP) files prospectus supplement under Rule 424(b)(3)",
            "Hyperliquid Strategies Inc (Nasdaq: PURR) authorizes $250 million share repurchase",
            "Hyperion DeFi, Inc. (Nasdaq: HYPD) reports second-quarter results as HYPE treasury tops 1.7 million",
            "Stripe's Bridge to support USDH issuance on HyperEVM",
            "Hyperliquid's HYPE token jumps after ICE chief calls it 'bigger than Nasdaq'",
            "VanEck files S-1 for spot HYPE ETF with staking",
            "Grayscale's HYPE ETF renamed Grayscale Hyperliquid Staking ETF",
            "Hyper Foundation proposes burning HYPE held in the Assistance Fund",
            "Hyperliquid (HYPE) rises 8% as Bitwise fund draws inflows",
            "Arthur Hayes says he sold all of his $HYPE.",
            "Kraken adds HYPE/USD and HYPE/EUR spot pairs for U.S. clients",
            "Coinbase Derivatives to list HYPE futures, citing demand from U.S. traders",
            "Is Hyperliquid Bigger Than Nasdaq? ICE's Sprecher Thinks So",
            "Hyperliquid Market Share Slips as Aster and Lighter Gain in Perps",
            "Hyperliquid Treasury Company Hyperion DeFi Raises $100 Million",
            "Hyperliquid-based USDH reaches $500 million in supply",
            "HyperLiquid DEX tops $300 billion in monthly perps volume",
            "Hyperliquid Collateral Rules Tighten After HYPE Price Swing",
            "What Is Hyperliquid? A Guide to the Onchain Perp Exchange Behind the New ETFs",
            "Sonnet BioTherapeutics adopts Hyperliquid treasury strategy, renames itself Hyperliquid Strategies",
            "Hyperliquid Funding Rates Flip Negative as HYPE Slides",
            "Deribit lists HYPE options as open interest in Hyperliquid perps climbs",
            "What Is Hyperliquid? Inside the Perp DEX Wall Street Is Watching",
            "Who Is Hyperliquid's Biggest Rival? Aster, Says Bitwise",
            # All caps.
            "BITWISE HYPERLIQUID ETF BEGINS TRADING ON NYSE ARCA",
            "ICE CHIEF: HYPERLIQUID IS BIGGER THAN NASDAQ",
            "WHAT IS HYPERLIQUID? INSIDE THE PERP DEX WALL STREET IS WATCHING",
            # After a question word the copula does not skip the name; "Is the" is taken
            # back by rule 2 with perps/DEX context.
            "Why Is Hyperliquid Up Today? HYPE Climbs as Perps Volume Surges",
            "Hyperliquid Is the Largest Onchain Perp DEX, Bitwise Says",
            # Sentence case: a lowercase copula or "is the" is not the adjective.
            "Hyperliquid is the new Nasdaq, ICE CEO says",
            "The biggest winners of the ETF approvals are Hyperliquid and Aster",
            # Token phrasing in Title Case, Upbit-style pairs, and "Is the" with venue context.
            "CME Group to Launch HYPE Futures in December",
            "Coinbase Derivatives Adds HYPE Futures, Expands Crypto Lineup",
            "Robinhood Lists HYPE Token for U.S. Customers",
            "HYPE Token Listed on Upbit",
            "Upbit Lists HYPE; KRW-HYPE Market Opens",
            "HYPE Treasury Firm Raises $500 Million",
            "Hyperliquid Is the Most Profitable Crypto Venue, Says JPMorgan",
            "Nasdaq Becomes Hyperliquid's Biggest Rival, Says ICE",
        ],
        "neg": [
            "Cutting Through the Hype: SEC Staff Statement on AI Washing",
            "BEYOND THE HYPE: TOKENIZATION AND THE FUTURE OF SETTLEMENT",
            "Don't Believe the HYPE: Grayscale Says Staking ETFs Need Clear Rules",
            "Banca Sella's HYPE launches bitcoin and ether trading for 1.9 million customers under MiCA license",
            "HYPE, the Italian e-money institution, adds crypto custody and staking via Conio",
            "Hyper Bit Technologies Ltd. (CSE: HYPE) Expands Dogecoin and Litecoin Mining Operations in Quebec",
            "Hyper Bit Technologies (Cboe Canada: HYPE) launches blockchain cold storage wallet ring",
            "Hyper Bit Technologies Ltd. (CSE:HYPE) (FSE: 0XX) announces crypto token treasury strategy",
            "iShares EUR High Yield Corp Bond ESG PAB UCITS ETF (HYPE) lists on Xetra, BlackRock says",
            "Scale Computing Launches SC//HyperCore Imaging Service as customers flee perpetual license costs",
            "Holepunch, backed by Tether, ships Hypercore 11 peer-to-peer ledger for its Keet app",
            "Hubble Protocol's USDH stablecoin regains its peg on Solana after crypto sell-off",
            "Hedera Council approves HIP-1215 for native token staking rewards",
            "Hyperledger Foundation becomes LF Decentralized Trust, expands blockchain projects",
            "Treasury market remains hyperliquid even under stress, Fed staff note says",
            "Why Hyperliquid Treasuries Still Anchor Stablecoin Reserves",
            "Hyperliquid Collateral Pools Help Tokenized Deposits Settle Faster, BIS Paper Finds",
            "Hyperliquid Money Market Funds Draw Record Inflows as Rates Fall",
            "Are Hyperliquid Government Bonds Safe Collateral for Tokenized Money Market Funds?",
            "Hyperlane (HYPER) lists on Upbit KRW market; bridge token jumps",
            "AI HYPE ETF FLOWS SURGE AS INVESTORS CHASE CHIPMAKERS",
            "CRYPTO HYPE VS. REALITY: SEC COMMISSIONER ON TOKENIZED SECURITIES",
            "Crypto HYPE vs. reality: Commissioner speech on tokenized securities and staking",
            "Bitwise CIO: bitcoin rally is more than hype as ETF inflows grow",
            "Hypera Pharma (HYPE3) shares rise after earnings",
            "Hypebeast shares slump; crypto NFT unit closes",
            "Kinetiq-style liquid staking hype fades as ETH restaking yields fall",
            "SEC charges promoters who used social media HYPE to pump crypto tokens",
            "Fed's Barr: stablecoin hype should not outrun safeguards",
            "Stablecoin Reserves Must Be Hyperliquid, Fed's Barr Tells Crypto Conference",
            "Fed Paper: Hyperliquid U.S. Treasuries Remain the Global Safe Asset",
            "Hyperliquid Markets Can Still Seize Up, Fed Governor Warns",
            "Hyperliquid Stocks Like Nvidia Dominate Retail ETF Flows",
            "Hyperliquid T-Bills Back Most Payment Stablecoins, Report Finds",
            "Why Hyperliquid Treasuries Still Anchor Crypto Stablecoin Reserves",
            "Tokenized Treasury Funds Offer Hyperliquid Collateral for DeFi Lenders",
            "SEC Commissioner: Tokenized Money Funds Are Hyperliquid Assets on the Blockchain",
            "Hyper Bit Technologies ($HYPE.CN) adds Dogecoin miners and crypto cold wallets",
            "Scale Computing posts record order book as VMware customers move to SC//HyperCore",
            "Scale Computing's HyperCore wins retail edge deals; order book up 40%",
            "Hubble Protocol relaunches USDH stablecoin for crypto-native markets on Solana",
            "HYPE, the Italian digital bank owned by Banca Sella, targets crypto-native markets",
            "Hubble's USDH Targets Crypto Native Markets After Solana Revival",
            "SEC Charges HyperFund Co-Founders in $1.7 Billion Crypto Mining Scheme; HyperVerse promoters barred",
            "$HYPER rallies as Hyperlane expands cross-chain bridge to Upbit users",
            "Kinetiq's kHYPE liquid staking token depegs briefly after validator outage",
            "Hyper-Liquid Treasuries and Tokenized Deposits: A Primer for Bank Treasurers",
            "Hyperliquidity in Tokenized Money Market Funds Worries Fed Staff",
            "Hypernative raises $40 million for blockchain threat monitoring",
            "Hyperledger Besu powers Canton-style tokenized deposit pilot at HSBC",
            "Treasury Market Remains Hyperliquid Even Under Stress, Fed Staff Note Says",
            "Hyperliquid Treasuries Beat Staking Yields for Corporate Cash, CFOs Say",
            "Can Tokenized Money Funds Stay Hyperliquid in a Run? Fed Paper Weighs On-Chain Redemptions",
            "Hubble Brings USDH Back to Web3 Native Markets and DeFi Lenders",
            "Hyperliquid Bonds and Staking ETFs: Where Pension Funds Park Cash Now",
            "The Treasury Market Is Hyperliquid, and Stablecoin Issuers Know It",
            "Why the Tokenized Treasury Market Is Hyperliquid",
            "Money Funds Were Hyperliquid. Then Came March 2020",
            # The finance adjective before asset nouns, after degree words and as an
            # object complement.
            "Hyperliquid Deposits: Why Banks Fear Stablecoin Runs Citi analysts say deposits could flow to stablecoins.",
            "Why Treasuries Are Hyperliquid And Stablecoin Reserves Should Hold Them JPMorgan analysts say tokenized Treasury funds could serve as collateral.",
            "Tokenized Treasuries Are More Hyperliquid Than Bank Deposits, Fed Paper Finds",
            "Keep Stablecoin Reserves Hyperliquid, Fed Governor Urges",
            "Making Tokenized Money Market Funds Hyperliquid: DTCC Collateral Paper",
            "How Hyperliquid Is the Treasury Market?",
            "The Most Hyperliquid Repo Market in the World Faces a Tokenization Test",
            "SEC: Money Market Funds Must Hold Hyperliquid Investments",
            "Why Stablecoins Must Be Backed by Hyperliquid, High-Quality Assets",
            "The Hyperliquid Dollar: Stablecoins and the Future of Money, Fed Speech",
            "Hyperliquid Portfolios and the Next Liquidity Crisis",
            # A title that ends in "Is/Are Hyperliquid", followed by its excerpt.
            "Why BlackRock Says the Treasury Market Is Hyperliquid Tokenized money funds rely on it, the firm said.",
            "The Treasury Market Is Hyperliquid The paper examines stablecoin reserves.",
            "Why the Tokenized Treasury Market Is Hyperliquid Stablecoin issuers hold short-dated bills, the note says.",
            "Why U.S. Treasuries Are Hyperliquid Even in a Crisis",
            # All caps.
            "STABLECOIN RESERVES MUST BE HYPERLIQUID, FED'S BARR SAYS",
            "HYPERLIQUID TREASURIES STILL ANCHOR STABLECOIN RESERVES",
            # The iShares UCITS ETF whose ticker is HYPE.
            "iShares HYPE ETF sees record outflows as high-yield bond spreads widen",
            "iShares HYPE ETF sees record outflows as BlackRock tokenized fund draws crypto inflows",
            # Generic words (staking, DEX, an all-caps HYPE) do not take the adjective
            # back; neither does derivatives vocabulary after a copula.
            "Stablecoin Reserves Must Be Hyperliquid, JPMorgan Says The bank also launched ETH staking for clients.",
            "Tokenized Treasuries Are More Hyperliquid Than Bank Deposits, JPMorgan Paper Finds. The paper also covers ETH staking.",
            "Why Stablecoins Must Be Backed by Hyperliquid, High-Quality Assets, BlackRock Says The firm also runs a staking ETF.",
            "Making Tokenized Money Market Funds Hyperliquid: DTCC Collateral Paper on DEX settlement",
            "BEYOND THE HYPE: STABLECOIN RESERVES MUST BE HYPERLIQUID, FED'S BARR SAYS",
            "Treasuries Look Hyperliquid, BlackRock Says",
            "Collateral Must Be Hyperliquid, CFTC's Pham Says in Speech on Perpetual Futures",
            "BEYOND THE HYPE TOKENS: STABLECOIN RULES",
        ],
    },
    # DOGE
    "dogecoin": {
        "pos": [
            "SEC Approves Listing of 21Shares Dogecoin ETF on Nasdaq Under Ticker TDOG",
            "Grayscale Dogecoin Trust ETF (GDOG) Begins Trading on NYSE Arca",
            "REX-Osprey DOGE ETF debuts on Cboe BZX as the first U.S. fund offering dogecoin exposure",
            "House of Doge Completes Merger with Brag House Holdings and Set to Trade on Nasdaq Under Ticker HODO",
            "CleanCore Solutions acquires an additional 100 million DOGE for its official Dogecoin treasury, backed by House of Doge",
            "Coinbase Derivatives to list DOGE futures alongside XRP and Solana contracts",
            "Bitwise to close and liquidate its Dogecoin ETF (BWOW) after rivals capture most of the inflows",
            "SEC charges promoters of fraudulent dogecoin cloud-mining scheme that raised $12 million from retail investors",
            "Dogecoin Foundation and Robinhood partner to expand DOGE payments for merchants",
            "DOGECOIN FUTURES VOLUME SURGES AT CME AS FUNDS HEDGE MEMECOIN EXPOSURE",
            "Federal Reserve staff note examines stablecoin and crypto volatility, citing Bitcoin, Ether and Dogecoin price swings",
            "$DOGE jumps 8% after Grayscale files amended S-1 for spot fund",
            "Dogecoin ETF inflows rise as Elon Musk steps back from the Department of Government Efficiency",
            "Upbit resumes KRW-DOGE deposits after Dogecoin network upgrade",
            "Treasury company Thumzup buys 7.5 million DOGE, taking holdings to 19 million DOGE tokens",
            "Dogecoin, the meme coin that started as a joke, gets its first spot exchange-traded fund in the U.S.",
            "Dogecoin (DOGE), created in 2013 as a reference to the Doge meme, wins SEC nod for first spot fund",
            "U.S. regulators clear first dogecoin exchange-traded fund, Reuters reports",
            "Dogecoin exchange-traded fund draws inflows even as Musk's Department of Government Efficiency winds down",
            "Bybit lists DOGE/USDT perpetual futures with 50x leverage for institutional clients",
            "Dogecoin slides as DOGE cuts gains after SEC delays decision on spot fund",
            "Grayscale Dogecoin Trust files to convert into exchange-traded fund; memecoin named after Doge meme",
            "Dogecoin price: DOGE price holds as spot ETF nears decision",
            "Binance Futures will launch USDⓈ-M DOGEUSDC perpetual contract with up to 50x leverage",
            "Grayscale files amended S-1 for a spot DOGE exchange-traded product",
            "DOGE's price jumps 9% after 21Shares' TDOG fund draws record inflows",
            "업비트, 도지코인(DOGE) 원화 마켓 입출금 일시 중단…네트워크 업그레이드 지원",
            "House of Doge CEO Marco Margiotta rings the Nasdaq opening bell as HODO shares debut",
            "Dogecoin's hashrate hits a record as Litecoin merge-miners pile in",
            "Coinbase Derivatives launches nano Dogecoin futures for U.S. traders",
            "Dogecoin Foundation releases Dogecoin Core 1.14.9 with security fixes",
            "SEC staff statement says dogecoin and other memecoins are generally not securities",
            "Robinhood Crypto adds DOGE-USD and DOGE/EUR to its European trading app",
            "Grayscale Dogecoin Trust ETF (NYSE Arca: GDOG) sees first weekly outflow",
            "$DOGE rips 12% as Coinbase Derivatives volume in DOGE futures hits record",
            "DOGECOIN (DOGE-USD) SLIDES AS BITWISE CONFIRMS BWOW CLOSURE",
            "Dogecoin-based payments app from House of Doge adds merchant settlement in USDC",
            "Created as a nod to the Doge meme, Dogecoin (DOGE) now backs three U.S. spot funds",
            "Dogecoin, named after the Doge meme, jumps 10% as Robinhood adds DOGE payments",
            "Dogecoin's rival memecoins lag as DOGE price rallies on ETF inflows",
            "Dogecoin Rallies as Shiba Inu, a Rival Meme Coin, Slumps",
            "CleanCore's DOGE holdings of 733 million tokens now exceed its cash",
            "Dogecoin, inspired by the Doge meme, gets its first Grayscale ETF",
            # Naming the agency alone does not skip the rule.
            "Dogecoin jumps 10% as Musk leaves the Department of Government Efficiency",
            # Agency phrases do not skip it when dogecoin is the subject of a price move.
            "Dogecoin jumps 8% as DOGE team wraps up work in Washington",
            "Dogecoin slides as Musk's DOGE cuts face court challenge",
            "Dogecoin falls as DOGE staffers leave; memecoin traders shrug",
            "Dogecoin price rises after Musk says DOGE access to Treasury was lawful",
            "Dogecoin rallies as DOGE officials testify before Congress",
            "Dogecoin rallies after Musk's DOGE team leaves Washington",
            "Dogecoin slides as DOGE staff exit the Treasury; crypto traders shrug",
            "DOGE Service ends; Dogecoin price jumps 8% as Musk returns to Tesla",
            # Only "Dogecoin Cash" is the fork.
            "Dogecoin cashes in on ETF approval, jumps 12%",
            "Robinhood launches Dogecoin cashback rewards for crypto card users",
            "Dogecoin cash-out volumes spike on Coinbase",
        ],
        "neg": [
            "The Department of Government Efficiency (DOGE), a nod to Musk's favorite cryptocurrency dogecoin, cuts SEC staff",
            "Musk's DOGE, named after the dogecoin meme, gains access to Treasury payment systems",
            "DOGE staffers join review of the SEC's crypto task force as agency trims budget",
            "House subcommittee on DOGE examines putting federal spending on a blockchain ledger",
            "DOGE explores moving government payments onto a blockchain, sources say; crypto industry cheers",
            "Treasury ends DOGE access to payment systems; bitcoin and crypto markets unmoved",
            "The DOGE price tag: $21.7 billion in claimed savings questioned by crypto-friendly lawmakers",
            "$2 billion DOGE cuts hit Federal Reserve contractors as stablecoin bill advances",
            "Trump floats $5,000 DOGE dividend checks as bitcoin and crypto rally",
            "Baby Dogecoin listed on Binance as memecoin mania returns",
            "Shiba Inu, the self-proclaimed Dogecoin killer, launches Shibarium layer-2 blockchain",
            "Dogechain bridge exploited; DC token falls 40%",
            "Doge of Venice exhibition at the Doge's Palace sells tokenized NFT tickets on a blockchain",
            "Dogelon Mars (ELON) token jumps 30% on crypto exchange listing",
            "The 2025 DOGE cuts left the SEC's crypto unit understaffed, inspector general says",
            "Former DOGE engineers launch stablecoin payments startup backed by crypto funds",
            "Doge staff accessed Treasury systems holding crypto tax data, lawsuit says",
            "Dogecoin20 presale raises $10 million as memecoin investors pile in",
            "DOGE Treasury probe: judge blocks access to payment data as crypto firms watch",
            "Texas DOGE Committee recommends a state bitcoin reserve and blockchain procurement records",
            "DOGE mining of taxpayer data raises privacy concerns among crypto advocates",
            "OPM says Musk's DOGE, whose name was a nod to a cryptocurrency, no longer exists; dogecoin slips",
            "Kabosu, the Dogecoin mascot who inspired the Doge meme, dies at 18; memecoin traders pay tribute",
            "DOGE funding cuts to CFPB spark debate over crypto oversight",
            "About 40 DOGE employees remain at federal agencies; stablecoin rules unaffected",
            "Musk's DOGE team audits Fort Knox gold; bitcoin reserve advocates weigh in",
            "DOGE fund freeze hits crypto research grants at federal agencies",
            "Texas DOGE reserves judgment on bitcoin reserve bill, crypto lobby says",
            "DOGE price cuts on federal software contracts anger crypto vendors",
            "More than 100 DOGE and OPM staff reassigned; crypto task force intact",
            "Dogecoin Cash token airdrop draws scam warnings from crypto exchanges",
            "Musk-led DOGE, a tribute to his favorite memecoin dogecoin, wraps up work at the SEC",
            "U.S. DOGE Service winds down; dogecoin fans and crypto traders shrug",
            "Grayscale unveils DOGE Trustee board; crypto fund",
            "Musk's Doge, named after his favourite cryptocurrency, dogecoin, gets access to Treasury payment systems",
            "Named after the memecoin dogecoin, Musk's DOGE has cut a fifth of the SEC's enforcement staff",
            "DOGE, whose name is a play on dogecoin, seeks access to Federal Reserve payment data",
            "Musk-led DOGE, which took its name from dogecoin, gains access to Fed payroll records",
            "DOGE, the agency that shares its name with dogecoin, disbands eight months early",
            "Former DOGE staffer, who called the agency's name a dogecoin joke, joins a crypto custody startup",
            "Inside the House of Doge: how Musk's cost-cutters took over Washington's payment rails",
            "DOGE price-cutting push on federal IT contracts rattles crypto custody vendors",
            "DOGE Trust Fund access in spotlight at Social Security hearing",
            "Senators say DOGE Trust Fund review will coincide with Social Security audit",
            "Democrats Probe DOGE Trust Fund Access as Bitcoin Reserve Bill Stalls",
            "More than 100 DOGE, OPM and GSA staffers reassigned; crypto task force intact",
            "Shiba Inu, a dogecoin rival, jumps 20% after Coinbase adds it to its derivatives exchange",
            "Dogecoin-style memecoins like Floki and Bonk draw an SEC investor alert on pump-and-dump schemes",
            "Kabosu, the Shiba Inu whose face launched dogecoin, is honored with a bronze statue in Sakura",
            "Wrapped Dogecoin (WDOGE) bridge on Ethereum paused after exploit",
            "Binance-Peg Dogecoin supply on BNB Chain falls as bridge usage drops",
            "머스크의 정부효율부(DOGE), 도지코인에서 이름 따와…SEC 인력 감축 착수",
            "DOGE's price tag for the Fed building audit tops $10 million, crypto lawmakers say",
            "DOGE price reviews put federal software contracts in the spotlight; crypto vendors wary",
            "In a nod to dogecoin, Musk's cost-cutting office was dubbed DOGE; its SEC review ends",
            "FY25 DOGE: $160 billion in claimed savings questioned; crypto reserve spared",
            "DOGE holdings of taxpayer data questioned by crypto privacy advocates",
            "Named after dogecoin, Musk's Doge has cut SEC staff by a fifth",
            "DOGE's namesake, dogecoin, was Musk's favorite coin; the agency now winds down at the Fed",
            "베이비도지코인, 바이낸스 상장 후 급등",
            # Look-alikes and more ways of explaining the agency's name.
            "Floki, a Dogecoin Copycat, Jumps 20% After Binance Listing",
            "Trump memecoin outpaces Dogecoin clones as crypto traders chase celebrity tokens",
            "Dogecoin-like memecoin Bonk jumps 30% on Solana",
            "Shiba Inu and other dogecoin rivals rally as memecoin volumes climb",
            "Musk's DOGE, which shares an acronym with the dogecoin memecoin, sought SEC records",
            "DOGE — its moniker lifted from dogecoin — gets access to Fed payment data",
            "Department of Government Efficiency (DOGE) - named in a wink at Dogecoin - audits Fed",
            "The Department of Government Efficiency, an acronym that evokes Dogecoin, targets the Federal Reserve",
            "DOGE, cheekily referencing Dogecoin, sends team to the SEC",
            "Elon Musk's Department of Government Efficiency, known as DOGE after the Dogecoin cryptocurrency, reviews Treasury payments",
            "The Department of Government Efficiency — or DOGE, like the dogecoin memecoin Musk promotes — gains access to Treasury payment system",
            "Senate grills DOGE; name a joke about Dogecoin, Musk said",
        ],
    },
    # LINK
    "chainlink": {
        "pos": [
            "Swift and Chainlink complete live tokenized fund transfers with UBS Asset Management",
            "DTCC selects Chainlink Runtime Environment for its Collateral AppChain",
            "SEC approves listing of Grayscale Chainlink Trust ETF (GLNK) on NYSE Arca",
            "ANZ uses Chainlink's CCIP for cross-border tokenized asset settlement",
            "ChainLink oracle network to bring central bank rate data on-chain",
            "CHAINLINK LABS JOINS DTCC SMART NAV PILOT WITH JPMORGAN AND BNY",
            "Euroclear pilot moves tokenized bonds across ledgers via CCIP. The Cross-Chain Interoperability Protocol (CCIP) connects public and private blockchains.",
            "$LINK jumps 12% as whales accumulate ahead of Swift integration",
            "The Trust may only hold LINK tokens existing on the Ethereum network, the prospectus says",
            "Upbit resumes KRW-LINK deposits after network upgrade",
            "XRP, LINK and HBAR lead altcoin rally after SEC adopts generic listing standards",
            "Mastercard partners with Chainlink to let cardholders buy crypto on-chain",
            "Bitwise files for spot ETF; LINK/USD rises 5% on the news",
            "SEC Crypto Task Force meets Chainlink Labs co-founder Sergey Nazarov on tokenization",
            "Fidelity International, Sygnum and Chainlink bring fund NAV data on-chain",
            "Hong Kong Monetary Authority e-HKD pilot with Visa and ChainLink",
            "LINK Token Rallies After ETF Approval",
            "$LINK staking v0.2 opens to institutional node operators",
            "Chainlink Launches CCIP 2.0 With Cross-Chain Verifiers for Institutional Digital Assets",
            "CHAINLINK'S RUNTIME ENVIRONMENT GOES LIVE FOR BANK TOKENIZATION WORKFLOWS",
            "Chainlink Foundation publishes roadmap for the next LINK staking pool",
            "Grayscale Chainlink Trust ETF (NYSE Arca: GLNK) files annual report; the Trust's only assets are LINK tokens",
            "SmartContract ChainLink Ltd white paper described a decentralized oracle network for smart contracts",
            "Chainlink (LINK) climbs after DTCC names its Collateral AppChain partners",
            "$LINK outflows from exchanges accelerate as on-chain data show accumulation",
            "Coinbase International lists LINK-USDC perpetual futures",
            "Upbit briefly suspends LINK/KRW trading during wallet maintenance",
            "BTC & LINK slip as altcoin traders de-risk ahead of FOMC decision",
            "Solana DeFi apps gain access to bridged assets as CCIP cross-chain transfers go live",
            "Banks remain on the fence about public chains, yet Chainlink pilots with Swift continue",
            "Bank of England wants stablecoin reserves ring-fenced; Chainlink Proof of Reserve pitched as a monitoring tool",
            "Chainlink Panel at Sibos: banks weigh tokenized deposits and interoperability",
            "Chainlink Posts Record Staking Deposits as Node Operators Expand",
            "Chainlink-powered Proof of Reserve adopted by a state stable token commission",
            "Identity startup's Mesh ID beta runs on Chainlink oracles",
            "On-chain data: whales keep accumulating $LINK.",
            "Sergey Nazarov of Chainlink Labs testifies on tokenization before House Financial Services subcommittee",
            # "defence" and "ring-fence company" are not fence-trade words.
            "Chainlink to power tokenised gilt pilot as UK defence companies seek on-chain supply-chain records",
            "Chainlink partners with a European bank on tokenised defence bonds as defence industry funding moves on-chain",
            "UK oil ring-fence company tokenises royalty stream using Chainlink oracles",
            "UK oil ring fence company tokenises royalty stream using Chainlink oracles",
            "Swift and Chainlink Test Cross-Border Payments With Banks",
        ],
        "neg": [
            "Chainlink fence installed around Federal Reserve Bank construction site",
            "Chainlink Fencing imports face new Commerce Department tariffs",
            "CHAINLINK FENCE MAKERS SEEK TARIFF RELIEF",
            "Chainlink-fence perimeter secures new bitcoin mining facility in Texas; crypto miners expand",
            "ChainLink Research: blockchain in supply chain still stuck in pilot stage",
            "ChainLink Solutions expands freight brokerage, adds stablecoin payment option",
            "Chainlink Services LLC wins county fencing contract",
            "Interlink Electronics ($LINK) reports Q2 revenue; bitcoin and crypto stocks also rally",
            "Small-cap movers: $LINK, $SMX rise as blockchain and crypto stocks rally; by the same token, sensor makers gained",
            "LINK tokenisation pilot for ATM withdrawals studied by the Bank of England",
            "Bank of England sets rules for recognised payment systems Bacs, CHAPS, FPS and LINK amid tokenised deposit work",
            "LINK Mobility Group reports Q3 results; ticker LINK on Oslo Bors, exploring blockchain messaging",
            "Link REIT issues tokenised green bond under HKMA Project Ensemble",
            "Plaid updates Link token flow for open banking payments; crypto exchanges integrate",
            "CMS finalizes Chronic Care Improvement Program (CCIP) changes alongside interoperability rule",
            "ENS expands CCIP-Read support for on-chain names across cross-chain resolvers",
            "CCI Paris Ile-de-France (CCIP) report on blockchain adoption by small firms",
            "Sound Transit Link light rail adds tokenized fare cards",
            "Chain Link Fence Manufacturers Institute comments on steel tariffs",
            "Oracle and Interlink shares rise; NASDAQ: LINK gains 8% on blockchain partnership rumor",
            "Market wrap: $LINK, $AAPL, $TSLA; bitcoin ETF flows and crypto stocks mixed",
            "Interlink Electronics ($LINK) adds tokens-based licensing for sensor SDK",
            "ETH Zurich study: a chain link in the settlement process fails; crypto exposure limited",
            "Commerce Adds Chainlink Mesh, Barbed Wire and Nails to Section 232 Steel Derivatives List",
            "Distributor adds black vinyl-coated Chainlink to Texas yards as data-center construction booms",
            "Texas bitcoin miner rings its site with galvanized steel Chainlink and adds 24-hour guards",
            "Chainlink Services, a local fencing contractor, wins $2 million school district bid",
            "Fence maker's Chainlink sales jump as crypto mining farms fortify sites",
            "Regional lender unveils ChainLink, a supply-chain finance portal for small importers",
            "SupplyChainLink Partners names new CFO, eyes blockchain freight tracking",
            "CHAINLINK RESEARCH: BLOCKCHAIN PILOTS IN FREIGHT STALL",
            "Whales pile into Interlink Electronics: $LINK up 38% on heavy options volume",
            "Illinois sues USDA over SNAP data demand; DOGE and LINK card records at issue",
            "Bank of England, LINK and ETH Zurich study offline payments as crypto adoption grows",
            "ENS adds CCIP-read gateway support for cross-chain name resolution",
            "Developers ship CCIP-Write (EIP-5559) so ENS records can be updated cross-chain",
            "ENS resolvers now query CCIP gateways for cross-chain names",
            "Chainlink Mesh Imports From Vietnam Face Antidumping Probe",
            "Stocktwits: $LINK.OL trending as LINK Mobility whales buy the dip after Q3 miss",
            "Illinois HFS updates LINK and LTC eligibility rules for Medicaid recipients",
            "SEC charges issuer over BTC-LINKED and USD-LINKED structured notes sold to retail",
            "Fed note: a weak chain link in cross-border payments slows settlement",
            "Illinois LINK card users can now pay online at more retailers; crypto not accepted",
            # Fence-industry text without crypto vocabulary, and "Chainlinked".
            "Fence Market to Reach $45 Billion by 2032; Wood, Vinyl and Chainlink Segments Analyzed",
            "Residential Fencing Market Report 2026: Chainlink Holds 30% Share",
            "Home Depot Recalls Chainlink Gate Latches Sold Nationwide",
            "Hurricane Damage: Chainlink and Wooden Fences Down Across Florida",
            "Chainlinked Funds: How Tokenized Assets Move",
        ],
    },
    # XMR
    "monero": {
        "pos": [
            "Treasury Sanctions Russian Ransomware Operators; SDN entry lists Digital Currency Address - XMR 49HqitRzdnhYjgTEAhgGpCfsjdTeMbUTU6cyR4JV1R7k2Eej9rGT8JpFiYDa4tZM6RZiFrHmMzgSrhHEqpDYKBe5B2ufNsL",
            "SEC Charges Darknet Marketplace Operators Who Laundered Proceeds Through Monero",
            "Binance to Delist Monero (XMR) on February 20, Citing Regulatory Compliance",
            "Kraken to end XMR trading for customers in the European Economic Area ahead of MiCA",
            "Europol: criminals increasingly turn to privacy coins such as Monero",
            "IRS-CI awards contracts to Chainalysis and Integra FEC to trace Monero transactions",
            "Monero completes FCMP++ hard fork, replacing ring signatures with full-chain membership proofs",
            "Qubic claims majority of Monero's hashrate, raising 51% attack fears",
            "MONERO SURGES AS PRIVACY COINS RALLY AFTER EU AMLR VOTE",
            "XMR jumps 12% as privacy coins rally on FCMP++ activation",
            "Fed's Barr: privacy-enhancing tokens like Monero pose AML challenges for banks",
            "EU AMLR bars crypto-asset service providers from handling anonymity-enhancing coins such as Monero and Zcash from July 2027",
            "DOJ: ransomware group demanded payment in XMR, then laundered it through instant exchangers",
            "XMR/USD falls 8% after exchange delisting notice",
            "Haveno, a decentralized exchange, lets users swap XMR for fiat without KYC",
            "CFTC charges trader with manipulating XMR perpetual futures on an offshore venue; $XMR fell 20%",
            "Monero Project releases v0.18.4 with wallet security fixes",
            "SEC Crypto Task Force meets privacy advocates on Monero and Zcash; Wrapped Monero also discussed",
            "Japan FSA pressed exchanges to drop anonymity coins; Coincheck delisted XMR, Dash and ZEC",
            "FinCEN proposes rule on anonymity-enhancing cryptocurrencies including Monero",
            "Monero 0.18.4.0 'Fluorine Fermi' released with wallet and node fixes",
            "Monero Zero-Day Flaw Let Attackers Crash Remote Nodes, Researchers Say",
            "Monero Gold Rush? Privacy Coin Hits Three-Year High as Exchanges Tighten KYC",
            "[거래지원종료] 모네로(XMR) 거래지원 종료 안내",
            "XMR-USD slides 7% in thin weekend trade",
            "XMR traders flock to Haveno as centralized venues pull listings",
            "Monero’s FCMP++ upgrade enters stressnet as developers eye a hard fork",
            "Valour lists Monero (XMR) ETP on Spotlight Stock Market",
            "$XMR rips 15% after FCMP++ activation",
            "MONERO (XMR) PRICE PLUNGES AFTER EXCHANGE DELISTING",
            "Developers mark Monero's 12th anniversary with FCMP++ hard-fork plan",
            "Delisting notice: XMR, ZEC and DASH to be removed from the platform on June 1",
            "SEC commissioner says privacy coins like Monero deserve a fair hearing on AML rules",
            "OFAC adds Monero wallet addresses tied to ransomware group to SDN List",
        ],
        "neg": [
            "Monero Classic (XMC) rallies 40% after Singapore team announces relaunch on crypto exchanges",
            "Monero-Classic, backed by AntPool, keeps CryptoNight proof of work for ASIC miners",
            "MoneroV (XMV) airdrop claims flagged as a scam by crypto researchers",
            "Monero Original (XMO) and Monero 0 (XMZ) forks list on crypto exchange HitBTC",
            "Wrapped Monero (WXMR) bridge on Ethereum pauses after smart contract audit",
            "Monero Gold (XMRG) token presale flagged by state securities regulators as crypto fraud",
            "Moneroo raises seed round to expand payment orchestration across Africa, adds stablecoin payouts",
            "Monerium receives e-money licence for EURe on-chain stablecoin, partners with Gnosis Pay",
            "XMReality (XMR:SS) wins remote-support order from Boliden mining unit",
            "OMXSTO:XMR shares rise as XMReality cites demand from mining and crypto data-centre clients",
            "XMReality AB (STO: XMR) signs framework agreement with a blockchain infrastructure operator",
            "Reuters: XMR.ST up 9% after XMReality wins wind-turbine order; token-based licensing model expands",
            "Cape Canaveral Skid Strip (XMR) to host crypto-funded startup's rocket landing test",
            "Actor Mark Monero joins cast of crypto heist thriller",
            "La monero estas en la poŝo: Esperanto league launches crypto education course",
            "XMRig cryptojacking malware found on bank servers, CISA warns crypto-mining attacks rise",
            "Wownero developers mock privacy coin rivals in new release",
            "SEC charges bitcoin mining scheme promoters; Exchange Act violations alleged (Release No. 34-99999, XMRX file)",
            "Moneta Markets fined by FCA over crypto CFD promotions",
            "MONERO GOLD (XMRG) TOKEN PRESALE HALTED BY STATE SECURITIES REGULATOR AS CRYPTO FRAUD",
            "WRAPPED MONERO (WXMR) BRIDGE HALTS WITHDRAWALS AFTER SMART CONTRACT EXPLOIT",
            "Monero Zero (XMZ) fork token lists on a small crypto exchange, drawing scam warnings",
            "Actor Mark Monero joins crypto-heist drama; Monero plays a hacker who launders stolen bitcoin",
            "ACTOR MARK MONERO CAST AS BITCOIN LAUNDERER IN STREAMING THRILLER",
            "Wrapped XMR (WXMR) token debuts on Ethereum decentralized exchanges with $2 million liquidity",
            "XMReality AB (Nasdaq First North Growth Market: XMR) wins remote-guidance order from a mining group",
            "XMR SS Equity: shares jump 11% after remote-support deal with a crypto-mining data centre operator",
            "Bitcoin billionaire's private jet uses XMR, the Space Force runway at Cape Canaveral, before crewed SpaceX flight",
            "Hospital opens XMR suite combining X-ray and MR imaging; board cites patient privacy safeguards and new tokens for staff access",
            "Microsoft PlayReady update changes XMR license format with token-based key rotation for streaming apps",
            "Attackers deploy XMR-Stak miner on exposed Kubernetes clusters, CISA warns of crypto-mining campaigns",
            "모네로부터 영감을 받은 NFT 컬렉션, 코인 결제 도입",
            "Monero Classic's developers relaunch XMC token on a crypto exchange after two-year pause",
            "MONERO ORIGINAL (XMO) AND MONERO ZERO (XMZ) FORK TOKENS LIST ON A SMALL CRYPTO EXCHANGE",
        ],
    },
    # WBT
    "whitebit": {
        "pos": [
            "WhiteBIT EU secures MiCA authorization from Austria's FMA, expanding regulated crypto services across the EEA",
            "Visa and WhiteBIT launch Nova crypto debit card for EU residents; cards issued by Wallester AS, a Visa principal member",
            "WhiteBIT Coin (WBT) reaches $15 billion market capitalization following exchange expansion",
            "Whitechain relaunches as Ethereum Layer 2 on the OP Stack, keeping WBT as its native gas token",
            "Kraken adds WBT/USD and WBT/EUR trading pairs for European and U.S. clients",
            "Exchange tokens rally as BNB, OKB and WBT post double-digit gains after Fed rate decision",
            "WHITEBIT US obtains money transmitter licenses in additional states, registers as FinCEN money services business",
            "Ukraine's Ministry of Digital Transformation and Whitebit sign memorandum on blockchain education and virtual asset law",
            "Fidelity Digital Assets note: WBT token now among the largest exchange tokens by market value",
            "$WBT supply falls after quarterly buyback-and-burn, exchange says",
            "DTCC and Whitechain explore tokenized collateral pilot with W Group payment firms",
            "SEC staff statement on centralized exchange tokens cites WBT, BNB and OKB as examples of fee-discount tokens",
            "WBT coin hits record high as buyback programme continues",
            "Crypto exchange whitebit.com restricts services in sanctioned regions after EU guidance",
            "WBT, the fee token of a Lithuania-registered centralized crypto exchange, joins Kraken listings",
            "CEX tokens outperform: WBT and BNB gain as trading volumes recover",
            "WhiteBIT's WBT token climbs after the exchange completes its quarterly burn",
            "Whitechain's OP Stack migration cuts WBT gas fees by 90%, developers say",
            "WBT/USDT breaks above $90 as the exchange-token rally broadens",
            "$WBT outperforms bitcoin in September as exchange buybacks continue",
            "Burned WBT tokens total 3 million this quarter, bringing supply below 140 million",
            "Binance's BNB, OKX's OKB and WBT lead exchange-token gains after CPI print",
            "Top exchange tokens by market cap: BNB, OKB, WBT and BGB",
            "SEC acknowledges Nasdaq 19b-4 filing to list a spot WBT ETF",
            "Asset manager files S-1 for WhiteBIT Coin Trust that would hold WBT directly",
            "WhiteBIT \u0421oin (WBT) holders unlock up to 100% maker-fee discounts",
            "whitebit.eu opens to retail customers in Germany and France under its MiCA passport",
            "WHITEBIT EXCHANGE RAISES WBT STAKING REWARDS FOR EU CLIENTS",
            "FinCEN MSB registry now lists WhiteBIT US; two more states grant money transmitter licenses",
            "Exchange token (WBT) of Europe's largest crypto venue by traffic hits record ahead of burn",
            "Crypto exchange tokens rebound: WBT, OKB and BNB gain as volumes recover",
        ],
        "neg": [
            "Weebit Nano (ASX:WBT) signs ReRAM licensing deal with onsemi",
            "ASX close: Weebit Nano (ASX: WBT) jumps 12% while crypto exchange tokens slide on bitcoin sell-off",
            "Welbilt (NYSE: WBT) to be acquired by Ali Group for $24 per share in $4.8 billion deal",
            "SEC charges former employee with insider trading ahead of Ali Group deal; WBT shares rose 30% on the news",
            "Charlotte's WBT radio host discusses spot bitcoin ETF approvals and crypto regulation with SEC commissioner",
            "Fed research: rising wet-bulb temperature (WBT) threatens outdoor labor productivity in the South; blockchain data not used",
            "DTCC Learning launches web-based training (WBT) course on tokenized collateral and digital asset settlement",
            "World Bank Treasury (WBT) prices digital bond settled on blockchain; investors receive tokens representing the bond",
            "Wrapped bitcoin (WBTC) custody shake-up worries holders of exchange tokens and DeFi lenders",
            "Stocktwits trending: $WBT.AX rallies as Weebit Nano wins crypto-mining chip design contract",
            "WhiteBridge Network (WBAI) and Whitecoin (XWC) listed on centralized exchange amid token rally",
            "WBTV Charlotte investigates crypto ATM scams as exchange tokens gain popularity",
            "Protesters form a white chain around the central bank as stablecoin bill debate continues",
            "Chart: the white bit of each bar shows tokenized deposit flows settled on-chain",
            "The WB Television Network parent Warner Bros. Discovery explores blockchain royalties",
            "Webtoon Entertainment (Nasdaq: WBTN) shares rise; company mulls crypto payments",
            "Weebit Nano (WBT) climbs 5% as crypto exchange tokens slide on bitcoin weakness",
            "Welbilt (WBT) holders approve merger; SEC notes exchange token offers under tender rules",
            "Investors in the World Bank Treasury (WBT) digital bond can exchange tokens for conventional notes at maturity",
            "CFTC staff web-based training (WBT) covers centralized exchange clearing and tokenized collateral",
            "WEEBIT NANO LTD ( $WBT ) - Weebit Nano signs ReRAM licence agreement with Texas Instruments",
            "Weebit Nano Ltd (WBT) shares surge 18% even as crypto exchange tokens slump on bitcoin sell-off",
            "Welbilt ($WBT) jumps 30% on Ali Group bid as Stocktwits sentiment turns extremely bullish",
            "SEC charges trader with insider trading in Welbilt, Inc. (WBT) ahead of merger; proceeds moved to a centralized crypto exchange",
            "Charlotte's WBT radio host asks SEC Commissioner whether exchange tokens are securities",
            "Charlotte news-talk station WBT coins new nickname for bitcoin ATM scams",
            "Weebit Nano (ASX: WBT) update: WBT's ReRAM passes AEC-Q100 automotive qualification; crypto exchange tokens slide in broader market",
            "ASX evening wrap: WBT +14%, BRN +6% as bitcoin miners and exchange tokens rally",
            "Weebit (WBT) CEO: ReRAM demand from hardware wallets rises alongside exchange-token boom",
            "Weebit Nano's WBT shares hit record; CEX tokens also rally",
            "DTCC Learning web-based training (WBT) module explains centralized crypto exchange failures and tokenized collateral",
            "FINRA e-learning WBT: how customers exchange tokens on centralized crypto exchanges",
            "FEDS Notes: wet-bulb temperature (WBT) extremes raise cooling costs for bitcoin miners and centralized cryptocurrency exchange data centers",
            "World Bank Treasury (WBT) digital bond: holders exchange tokens for cash at maturity",
            "WBT-FM morning show: listeners ask how exchange tokens work",
            "WBTC/USDT and WBETH/USDT pairs suspended as exchange tokens slide",
            "SEC halts 'WhiteBitcoin' offering promoted as a centralized crypto exchange token",
            "Stocktwits: $WBT trending as ReRAM chipmaker wins Texas Instruments licence",
            "WBT AU shares jump 9% while crypto exchange tokens trade mixed",
        ],
    },
    # ADA
    "cardano": {
        "pos": [
            "CME Group to Expand Crypto Derivatives Suite with Launch of Cardano, Chainlink and Stellar Futures",
            "CME Group Announces First Trades for New Cardano, Chainlink and Stellar Futures",
            "Micro ADA futures begin trading on CME Globex; first block traded between Cumberland DRW and Wintermute",
            "SEC approves listing and trading of shares of Grayscale Cardano Trust ETF on NYSE Arca",
            "NYSE Arca files proposed rule change to list and trade shares of the 21Shares Cardano ETF",
            "Self-Regulatory Organizations; NYSE Arca, Inc.; Notice of Filing of a Proposed Rule Change to List and Trade Shares of the Grayscale Cardano Trust ETF under Rule 8.201-E. The Trust will hold ADA.",
            "Coinbase Custody named custodian for Grayscale's spot Cardano fund",
            "Cardano Foundation partners with Swiss bank to explore tokenized deposits for corporate treasuries",
            "Input Output Global and DTCC discuss on-chain collateral mobility at Sibos",
            "EMURGO launches USDA stablecoin on Cardano with Anzens",
            "Charles Hoskinson testifies before House Financial Services Committee on market structure bill",
            "Upbit resumes KRW-ADA deposits after network upgrade",
            "ADA/USD jumps 8% after SEC generic listing standards clear path for altcoin ETFs",
            "BTC, ETH and ADA lead crypto rally as the Fed cuts rates by 25 basis points",
            "$ADA whales accumulate ahead of spot ETF decision; altcoin volumes surge",
            "CARDANO BLOCKCHAIN ADOPTED BY ETHIOPIA MINISTRY FOR STUDENT RECORDS",
            "Franklin Templeton adds Cardano to institutional platform with staking support",
            "IOHK and Wyoming Stable Token Commission test state stable token settlement on Cardano",
            "Cardano's Chang hard fork activates on-chain governance for ADA holders",
            "Nasdaq-listed treasury company buys $100 million of Cardano, Bitcoin and Ethereum",
            "SEC Crypto Task Force meets with Cardano Foundation representatives on tokenization",
            "Cardano (ADA) added to CME CF New York Variant reference rates",
            "Hong Kong SFC approves first Cardano ETF for retail investors",
            "Bank of Canada study compares Solana, Cardano and Ethereum settlement finality",
            "Cardano network outage halts block production for seven hours",
            "Cardano ecosystem receives $70 million in treasury funding for institutional integrations",
            "Cardano community approves treasury withdrawal of 96 million ADA",
            "Wyoming's FRNT state stable token goes live on Cardano network",
            "Grayscale files S-1 for Grayscale Cardano Trust ETF, ticker GADA, with Coinbase Custody as custodian",
            "Cardano Foundation to present tokenized bond settlement pilot with Swift at Sibos",
            "Florida pension fund discloses stake in Grayscale Cardano Trust ETF in 13F filing",
            "Input | Output Global and DTCC test tokenized collateral settlement at Sibos",
            "Cardano (ADA) jumps 11% after CME Group confirms Micro Cardano futures launch",
            "$ADA and $XRP lead altcoin gains after SEC approves generic listing standards for crypto ETPs",
            "Bithumb suspends ADA deposits for Cardano mainnet upgrade; Upbit to follow",
            "ADA-USD slides 6% as Fed holds rates; bitcoin steady",
            "Intersect, the Cardano member organisation, ships node release for Plomin hard fork",
            "IOG, the research company behind Cardano, publishes Hydra audit results",
            "Cardano development activity leads crypto GitHub rankings for third straight month",
            "XRP, SOL and ADA ETFs: SEC sets deadlines for spot altcoin fund decisions",
            "$ADA slips 4% as crypto markets digest Fed minutes",
            "CARDANO FOUNDATION AND DTCC TO EXPLORE TOKENIZED COLLATERAL",
            "SEC Crypto Task Force meeting with Input Output Global on staking and DeFi",
            "Cardano renaissance: on-chain activity hits record as stablecoin supply grows",
            "Grayscale’s spot Cardano ETF draws $40 million on first day of trading",
            "Hoskinson says Cardano will integrate Chainlink oracles for institutional DeFi",
            "업비트, 카르다노(ADA) 하드포크 지원…입출금 일시 중단",
            "에이다(ADA) 현물 ETF 기대감에 12% 급등",
            "카르다노 재단, 스위스 은행과 예금 토큰화 실험",
            "그레이스케일, 카르다노 현물 ETF 상장 신청…가상자산 ETF 확대",
            "XRP and ADA lead crypto rally after SEC ends Ripple lawsuit",
            "Robinhood makes BTC, ETH and ADA accessible to retail crypto investors in the EU",
            "Mercer University researchers test Cardano blockchain for diplomas",
        ],
        "neg": [
            "Bitcoin ATM operator settles Americans with Disabilities Act (ADA) lawsuit over inaccessible kiosks",
            "SEC charges company with misleading investors about ADA compliance of its crypto kiosks and token sales",
            "Crypto exchange website sued under the ADA; plaintiff says blockchain tokens page fails screen readers",
            "GAO finds Antideficiency Act (ADA) violation in agency blockchain pilot contract",
            "SOL and ADA claims: court tolls statute of limitations in disability suit against crypto lender",
            "DOT and ADA rules require accessible fare systems as transit agency pilots blockchain tokens",
            "Assistant District Attorney: ADA charges crypto scammer in token fraud case",
            "American Dental Association (ADA) lets members pay dues in stablecoin, bitcoin",
            "Adacel Technologies ($ADA) wins FAA simulator contract; crypto stocks also rallied",
            "ASX: ADA shares jump after Adacel wins air traffic deal; bitcoin also higher",
            "Cardano Group completes acquisition of ACTIAM, adding sustainable investment and tokenisation research",
            "Mercer to acquire Cardano, the UK and Dutch pensions investment specialist, as LDI demand grows",
            "Cardano, the pensions investment specialist, warns trustees against crypto allocations",
            "Pensions specialist Cardano says LDI funds have cut leverage after gilt crisis; tokenised gilts not yet ready",
            "Cardano Risk Management tells Bank of England LDI review collateral settlement must speed up; blockchain no fix",
            "Fiduciary manager Cardano says digital assets remain unsuitable for DB schemes",
            "Cardano Development's TCX fund expands local-currency lending; digital asset strategy under review",
            "Cardano Advisory: covenant strength and the crypto exposure of scheme sponsors",
            "Gerolamo Cardano's cipher grille remains a staple of cryptography courses and crypto puzzles",
            "The Cardano grille: how a 16th-century crypto trick inspired modern encryption",
            "Cardano's formula and the cubic equation, explained for cryptographers",
            "Cardano al Campo residents oppose Malpensa cargo expansion as bitcoin miner eyes site",
            "An Input Output Global Value Chain Analysis of Tariffs: Fed note also examines blockchain supply chains",
            "Ada Lovelace Institute report on AI and crypto governance",
            "NVIDIA Ada Lovelace GPUs power crypto mining rigs, ADA-compliant data centers",
            "By the same token, Cardano argues DB schemes should hedge inflation before buyout",
            "Cardano reports stellar returns for Dutch pension clients as it takes a stake in Lincoln Pensions",
            "Cardano Insights: what the Pension Schemes Bill means for stake-holders and tokens of trust",
            "Now: Pensions owner Cardano names new chief executive; Mercer integration continues",
            "Cardano Investment launches Dutch pension transition fund amid Wtp reforms",
            "Cardano Sustainable Investment fund excludes crypto miners and blockchain energy users",
            "Stichting Cardano Development annual report: Impact Loan eXchange co-invests with development banks",
            "Cardano, cryptography and the Renaissance: a history of ciphers and secret writing",
            "Transit agency says DOT and ADA require accessible fare gates before blockchain ticket pilot",
            "Cardano: two sides of the same coin for DB schemes' endgame planning",
            "Dutch pensions group Cardano backs Bank of England digital gilt tokenisation pilot",
            "Mercer's Cardano unit tells DB trustees crypto remains too volatile for endgame portfolios",
            "CARDANO RISK MANAGEMENT B.V. SAYS BLOCKCHAIN SETTLEMENT OF REPO IS YEARS AWAY",
            "Cardano's LDI chief: tokenised gilts could ease collateral calls in the next crisis",
            "Mercer's bid for Cardano is more than a token gesture as consolidation sweeps investment consulting",
            "Cardano CIO tells trustees bitcoin is no inflation hedge",
            "ACTIAM rebrands as Cardano; responsible investment range keeps excluding crypto miners",
            "Bitcoin Miner Eyes Former Textile Mill in Cardano Al Campo Near Malpensa",
            "From Cardano to Enigma: National Cryptologic Museum traces 400 years of codebreaking",
            "From Cardano's dice to crypto markets: a Fed economist on the long history of speculation",
            "Cardano, the Renaissance gambler who first computed odds, would have understood crypto speculation",
            "Museum exhibit on the Cardano cipher and early crypto machines opens in Pavia",
            "Cardano's Formula Explained: What Crypto Traders Can Learn From 16th-Century Algebra",
            "Steganography Study Revives Cardano's Grid, Hiding Text in Grayscale Images",
            "FEDS Notes: Using Input Output Global Tables to Measure Exposure to Chinese Tariffs",
            "Cardano-based closed-form solver speeds cubic equation-of-state calculations for pipeline operators",
            "Cardano-Mercer deal closes; combined firm keeps crypto off default funds",
            "DOGE and ADA: Justice Department disability rights section shrinks as crypto enforcement unit is disbanded",
            "Judge rejects exchange's ADA and SOL arguments in blind trader's disability suit over bitcoin app",
            "Court: SOL and ADA defenses fail in suit by blind user against Coinbase over inaccessible app",
            "Benefits brief: ADA and LTC riders push coinsurance higher for retirees",
            "DOJ settlement requires ADA coin-operated laundry machines at 40 apartment complexes",
            "Adacel Technologies Ltd ($ADA) jumps 12% on air traffic contract; ASX crypto stocks mixed",
            "Midnight Network's NIGHT token lists on Kraken as privacy chain launches mainnet",
            "Lovelace Capital launches tokenized treasury fund on Ethereum",
            "ADA-compliant crypto ATM kiosks: FinCEN and DOJ issue joint guidance",
            "머서, 영국·네덜란드 연금 운용사 카르다노 인수 완료…가상자산 투자는 검토 안 해",
            "카르다노의 공식으로 푸는 3차 방정식…암호학의 역사 특강",
            "에이다 러브레이스 연구소, AI와 가상자산 규제 보고서 발표",
            "Cardano-inspired steganography hides messages in grayscale photos",
            "Cardano's head of liability-driven investment warns tokenised collateral is no quick fix",
            "Paratransit riders can still use ADA tokens after fare system upgrade",
            "CARDANO GROUP SAYS DIGITAL ASSETS REMAIN OFF LIMITS",
            "Cardano B.V. says digital assets stay outside client mandates",
        ],
    },
    # RAIN
    "rain": {
        "pos": [
            "Enlivex Treasury Update: Total RAIN Holdings Rise to 78,819,756,062 Tokens Enlivex Ltd. (Nasdaq: ENLV) today provided an update on its digital asset treasury.",
            "Enlivex Adopts Digital Asset Treasury Strategy Centered on RAIN Token RAIN serves as the Company's primary treasury reserve asset.",
            "Enlivex Revalues RAIN Token Treasury as Rain Protocol Gains Ground in Prediction Markets",
            "Nasdaq biotech firm bets $212m on new Arbitrum-based prediction market token Enlivex said it would acquire $212 million of Rain, the native token of the Rain Protocol.",
            "Rain readies V2 launch with a new liquidity pool Rain, a decentralized prediction markets protocol, says the pool opens before the World Cup.",
            "RAIN Token Jumps as Protocol Gains Ground in Prediction Markets Rain (RAIN) rallied after the Rain Foundation added liquidity.",
            "Rain Protocol Completes DAO Settlement With 7.4B $RAIN Token Burn The Arbitrum-based prediction markets protocol closed its Credit Refund claims process.",
            "Rain Surges As It Storms Into Prediction Markets Rain (RAIN), the governance token of the prediction market protocol, climbed after the V2 announcement.",
            "Rain V2 goes live on Arbitrum with on-chain order book ahead of FIFA World Cup",
            "SEC staff statement on crypto asset treasury companies Issuers such as Enlivex, which holds RAIN tokens as its primary reserve asset, must disclose valuation methods.",
            "CFTC staff advisory on decentralized event contracts names Polymarket and Rain Staff reviewed platforms including Rain, an Arbitrum-based prediction market protocol.",
            "Enlivex bets on Rain: Israeli biotech doubles down on prediction-market token treasury",
            "Kraken lists RAIN, governance token of the Arbitrum prediction markets protocol",
            "Arbitrum's Rain passes $500 million in open interest as World Cup markets close",
            "Rain's prediction markets processed record volume during the World Cup final, CEO Roy Shaham said",
            "Custodian added for Enlivex RAIN treasury Enlivex Ltd. said its RAIN tokens held on Arbitrum One are now under qualified custody.",
            "Enlivex Announces $212 Million Private Placement to Initiate Digital Asset Treasury Focused on RAIN",
            "Enlivex Ltd. (Nasdaq: ENLV) exercises option to buy additional RAIN tokens from the RAIN Foundation",
            "Report of Foreign Private Issuer (Form 6-K): Enlivex Ltd. Exhibit 99.1 Enlivex reports RAIN treasury valued at approximately $1.1 billion as of July 18, 2026",
            "Enlivex bets on Rain Protocol as biotech pivots to prediction-market token treasury",
            "Rain DAO settlement burns 7.4 billion $RAIN as the prediction markets protocol retires credit-refund claims",
            "Rain Protocol (RAIN) Price Prediction 2026: Can the Prediction Markets Token Hit New Highs?",
            "Arbitrum-based prediction market Rain hits $1 billion in weekly volume",
            "Rain, the Arbitrum-based prediction market, commits $100 million in liquidity for the World Cup",
            "Polymarket rival Rain (RAIN) jumps 30% after 7.4 billion token burn",
            "Rain’s decentralized prediction markets gain on Polymarket and Kalshi",
            "Rain V2 goes live; CEO Roy Shaham says the on-chain order book will anchor World Cup markets",
            "$RAIN rallies as Arbitrum prediction market Rain unveils V2 order book",
            "Rain Foundation deploys $100M liquidity pool; RAIN token climbs 20%",
            "Upbit lists Rain (RAIN) for KRW trading on the Arbitrum One network",
            "Arbitrum prediction market Rain launches V2 with $100 million liquidity pledge",
            "The Rain token (RAIN) climbed on Arbitrum-based prediction market volume",
            "21Shares files S-1 for spot RAIN ETP tracking the Arbitrum prediction markets token",
            "엔리벡스(Enlivex), 레인(RAIN) 토큰 보유량 796억 개로 확대",
        ],
        "neg": [
            "Rain raises $250M Series C to scale stablecoin-powered payments infrastructure for global enterprises Rain, a Visa Principal Member, supports USDC on Arbitrum, Base and Solana.",
            "Rain Expands Stablecoin Visa Cards to Solana, Tron and Stellar as digital payment gains momentum",
            "Stablecoin startup Rain is worth $1.95 billion and plans to issue Mastercard cards to institutional customers",
            "Polymarket teams up with card issuer Rain so prediction market winners can spend USDC anywhere Visa is accepted",
            "Visa expands stablecoin settlement to Arbitrum with partners including Rain, Bridge and Paxos",
            "Arbitrum DAO approves grant to Rain for stablecoin card rewards on-chain",
            "Bahrain crypto exchange Rain becomes first licensed crypto-asset member of Bahrain Association of Banks",
            "Rain acquires Digital Ma'arefa, publisher of The Finance Memo and Crypto Memo, as blockchain adoption grows in the Gulf",
            "Rain Enhancement Technologies Holdco, Inc. (Nasdaq: RAIN) signs letter of intent to combine with Tensor Networks, a predictive AI developer",
            "Rain Enhancement Technologies Holdco, Inc. Regains Compliance with Nasdaq Listing Requirements RAIN and RAINW continue to trade on the Nasdaq Capital Market.",
            "Rain Oncology Inc. (NASDAQ: RAIN) agrees to be acquired by Pathos AI in tender offer",
            "Impinj (Nasdaq: PI) reports record RAIN RFID endpoint IC shipments; RAIN Alliance adds blockchain supply-chain members",
            "Rainmaker ($RAIN) launches AI agents for sports prediction markets on Polymarket and Kalshi",
            "Top gainers: $RAIN (Rainmaker) and ARB (Arbitrum) lead AI agent tokens",
            "Raindrop ($RAIN) turns X feeds into a Solana perpetuals trading terminal",
            "Virtuals agent Rain (RAIN) onboards Ronin gamers with Llama-powered stats bot",
            "Rain Coin (RAIN) daily rewarding token expands to Base and BNB Chain",
            "rainlang (formerly Rain Protocol) ships Raindex v5 order book on Flare and Base",
            "Beige Book: Heavy Rain Slowed Construction Activity in Several Districts",
            "Prediction Markets Let Traders Bet on Rain, Snow and Heat as Kalshi Expands Weather Contracts",
            "Kalshi Launches Rain Prediction Markets for 20 U.S. Cities",
            "Make It Rain: Tokenized Treasury Funds Pull In $5 Billion as Crypto Rally Broadens",
            "The RAIN Protocol for Crypto Traders: Recognize, Allow, Investigate, Nurture during volatility",
            "RAIN Foundation and Aqua for All scale rainwater harvesting finance in Africa",
            "Rain Industries (NSE: RAIN) Q2 results: calcined petroleum coke volumes rise",
            "K-pop star Rain launches NFT collection on Ethereum blockchain",
            "Rain Bird Corporation adopts stablecoin payments for dealer settlement",
            "Prediction-market tokens rally: Rainmaker ($RAIN) jumps 35% as Solana and Arbitrum volumes climb",
            "Rainmaker ($RAIN) and Arbitrum (ARB) lead Tuesday's AI-agent token gainers",
            "SEC Charges Promoters of Raindrop ($RAIN) Token in Arbitrum Pump-and-Dump Scheme",
            "Rain Coin (RAIN) lists on Arbitrum-based DEX as daily-reward token expands",
            "AI-agent tokens rally: Virtuals' Rain (RAIN) up 40%, Arbitrum (ARB) up 8%",
            "RAIN LAUNCHES STABLECOIN VISA CARDS FOR BUSINESSES ON ARBITRUM AND BASE",
            "BAHRAIN'S RAIN ADDS ARBITRUM (ARB) AND ETHENA (ENA) TRADING FOR GCC CUSTOMERS",
            "Premarket movers: Enlivex (ENLV), Rain Enhancement Technologies (RAIN) and Impinj (PI) jump",
            "Biotech stocks moving: Rain Oncology (NASDAQ:RAIN) +12%, Enlivex Therapeutics (NASDAQ:ENLV) +9%",
            "RAIN to explore weather prediction markets with Tensor Networks, 8-K shows",
            "Arbitrum's Rain of Incentives: DAO Approves 50 Million ARB for DeFi Growth",
            "Arbitrum’s Rain Card Rewards Program Extended Through 2027",
            "Rain's prediction-market card lets Polymarket winners spend USDC at 150 million Visa merchants",
            "Gulf exchange Rain's prediction market launch wins Central Bank of Bahrain approval",
            "Rain is a prediction market staple: Kalshi weather contracts top $50 million",
            "Mastercard partners with Rain, the stablecoin card platform, on institutional prediction market payouts",
            "Stellar Development Foundation and Rain bring USDC-funded Visa cards to Stellar; Rain also supports Arbitrum, Base and Solana",
            "Raindex, the order-book app from the team behind Rain Protocol, goes live on Arbitrum",
            "The RAIN Protocol (Recognize, Allow, Investigate, Nurture) helps prediction market traders stop chasing losses",
            "Impinj: RAIN tags now anchor luxury-goods provenance records on Arbitrum",
            "RAIN CARDS LET POLYMARKET PREDICTION MARKET WINNERS SPEND USDC ON ARBITRUM",
            "Polymarket winners can now cash out to Rain V2 cards",
            "$RAIN, the Solana token behind Rainmaker's prediction-market agents, jumps as Arbitrum lags",
            "Arbitrum's Rain-Check on Stylus Upgrade Leaves Developers Waiting",
            "Arbitrum’s Rain Check on BoLD Upgrade Frustrates Validators",
            "Kalshi rain contracts: the prediction market platform Rain-or-Shine index debuts",
        ],
    },
    # XLM
    "stellar": {
        "pos": [
            "DTC's Tokenization Service to Connect with Stellar Public Blockchain as DTC Advances its Multi-Chain Strategy",
            "DTCC and the Stellar Development Foundation (SDF) expect DTC-tokenized assets to be available on the Stellar network in the first half of 2027.",
            "Visa expands stablecoin settlement to Stellar and Avalanche, adds PYUSD, USDG and EURC",
            "U.S. Bank tests stablecoin on the Stellar network",
            "Franklin Templeton's BENJI tokenized money market fund expands on Stellar",
            "SEC Crypto Task Force meeting with Stellar Development Foundation regarding tokenized securities",
            "CME Group Announces First Trades for New Cardano, Chainlink and Stellar Cryptocurrency Futures",
            "Grayscale Stellar Lumens Trust files Form S-1 to list shares on NYSE Arca",
            "PayPal USD stablecoin PYUSD goes live on Stellar",
            "Bermuda to build national onchain economy with Stellar and Circle",
            "MoneyGram launches USD stablecoin on Stellar, expanding cash-to-crypto access at retail locations",
            "Stellar's Denelle Dixon testifies before Senate Banking Committee on stablecoin legislation",
            "SEC approves listing of spot XLM ETF under generic listing standards",
            "Societe Generale-FORGE brings EURCV stablecoin to Stellar",
            "WisdomTree Launches Tokenized Government Money Fund on Stellar",
            "Franklin Templeton adds Soroban smart contracts to its onchain fund transfer agent",
            "DTCC Selects Stellar as First Public Blockchain for Tokenized Collateral",
            "Nasdaq CME Crypto Index adds XLM as a constituent",
            "Tokenized Treasuries Expand to New Public Chains. The fund is now available on Ethereum, Polygon and Stellar.",
            "Stellar Development Foundation Partners With Circle to Expand USDC Access",
            "Circle Expands EURC to Stellar-based Wallets Across Europe",
            "CME Group to launch Stellar (XLM) futures on October 19, pending regulatory review",
            "Stellar Launches Protocol 23 Upgrade on Mainnet With Faster Smart Contracts",
            "PayPal USD Stablecoin Goes Live on Stellar PayPal today announced that PYUSD is now available to users.",
            "Ondo Brings Tokenized Treasuries to Stellar NEW YORK, Oct. 1, 2026 /PRNewswire/ -- Ondo Finance today announced USDY availability.",
            "Franklin Templeton's Onchain Fund Now on Stellar, Ethereum and Arbitrum",
            "Mastercard and Stellar partner on stablecoin card settlement",
            "From Stellar to Solana: tokenized funds go multichain",
            "The Stellar Foundation said Denelle Dixon will speak at the SEC roundtable on tokenization",
            "Stellar Development Foundation invests in Archax to expand tokenized fund access",
            "Stellar partners with PayPal to bring PYUSD to more wallets",
            "Stellar joins Visa's stablecoin settlement program",
            "$XLM jumps 12% after DTCC picks Stellar for its tokenization service",
            "Stellar (XLM) rallies as CME Group confirms futures launch date",
            "21Shares Lists Stellar ETP on SIX Swiss Exchange The product gives investors physically backed exposure to XLM.",
            "NYSE Arca Files to Convert Grayscale Stellar Lumens Trust (GXLM) Into an ETF",
            "WisdomTree Physical Stellar Lumens ETP Crosses $100 Million in Assets",
            "Stellar Lumen (XLM) futures begin trading at CME",
            "스텔라루멘(XLM), DTCC 토큰화 서비스 연결 소식에 상승",
            "스텔라 루멘, 업비트 원화 거래량 상위권",
            "스텔라(XLM), 업비트 거래대금 1위",
            "Soroban smart contracts go live on Stellar mainnet",
            "MoneyGram Access Goes Live on the Stellar Network",
            "Binance to List XLM/USDC Perpetual Futures",
            "Stellar-native USDC now accepted by Visa merchants in Latin America",
            "Taurus Integrates Stellar Blockchain for Bank Custody Clients",
            "Franklin Templeton Picks Stellar, Ethereum for New Tokenized Fund",
            "USDC on Stellar surpasses $1 billion in payment volume",
            "DTCC Picks Stellar for Tokenized Collateral Pilot",
            "Paxos Launches USDG on Stellar Paxos today announced that its regulated stablecoin is now live.",
            "Circle Brings EURC to Stellar Circle Internet Group today announced that EURC is live on the network.",
            "Canary Files for Spot Stellar Lumens ETF With Nasdaq",
            "Upbit KRW-XLM market sees record volume after DTCC news",
            "The Stellar Network Processes Record USDC Volume in September",
            "Bitcoin, Ethereum and Stellar Lead Crypto Rebound as ETF Hopes Grow",
            "STELLAR DEVELOPMENT FOUNDATION AND DTCC ANNOUNCE TOKENIZED COLLATERAL PILOT",
            "Stablecoin Volumes on Stellar Hit Record",
            "In a blog post, Stellar said USDC transfers doubled",
            "SEC Delays Decisions on Stellar, Solana ETFs",
            "Stellar Hits Milestone as Tokenized Assets on Chain Top $1 Billion",
            "Stellar Teams Up With Circle to Expand USDC Access",
            "Stellar Surpasses $1 Billion in Real-World Assets",
            "Stellar Named Payment Rail for Ukraine's Digital Hryvnia Pilot",
            "Stellar Partners With Mastercard to Enable Crypto Credentials",
            "Exclusive: Stellar to Launch Tokenized Deposit Pilot With U.S. Bank",
            "MoneyGram, Stellar in Talks on Stablecoin Payments",
            "Why Banks Choose Stellar for Stablecoin Payments",
            "Visa Adds Stellar and Avalanche to Stablecoin Settlement",
            # Developer product names; verbs in subject position ("Circle and Stellar
            # Partner", "Stellar Surges 15%"); "Support for Stellar Tokenized Assets".
            "Stellar Anchor Platform Adds Support for Bank Tokenized Deposits",
            "Stellar Wallets Kit Adds Passkeys for Stablecoin Users",
            "Circle and Stellar Partner to Bring EURC to Europe",
            "MoneyGram, Stellar Partner on USDC Cash-Out",
            "Stellar Welcomes Bitso Stablecoin Launch",
            "Stellar Moves Into Tokenized Deposits With Bank Pilot",
            "Stellar Is Becoming the Chain of Choice for Tokenized Money Market Funds",
            "Stellar Surges 15% After Grayscale Files for Spot ETF",
            "Stellar Price Jumps 12% as ETF Hopes Grow; crypto markets",
            "Taurus Adds Support for Stellar Tokenized Assets",
            # A product after a listing or filing verb; "on Stellar" before a network
            # noun or a verb with a record; a Stellar-specific cue (SDF).
            "Grayscale Files for Spot Stellar ETF as Crypto Listings Expand",
            "CME Adds Stellar Futures as Crypto Derivatives Expand",
            "USDC on Stellar Hits Record Volume",
            "Bitso Launches Stablecoin on Stellar Mainnet",
            "SDF Says Stellar Network Processed Record USDC Volume",
        ],
        "neg": [
            "Retailer Posts Stellar Results for the Quarter",
            "Visa Posts Stellar Quarter as Payment Volumes Climb",
            "Tokenized Treasury Funds Post Stellar Growth in Third Quarter",
            "Coinbase Shares Jump on Stellar Crypto Trading Revenue",
            "Federal Reserve Board announces approval of application by Prosperity Bancshares, Inc. The Board approved the application to acquire Stellar Bancorp, Inc., and thereby indirectly acquire Stellar Bank, both of Houston, Texas.",
            "Stellar Bank Launches Instant Payments on the RTP Network",
            "Stellar Cyber Partners with Lumen Technologies to Expand Network Detection and Response",
            "Stellar Blade Sequel Announced for PlayStation Network and Nintendo Switch 2",
            "Microsoft disables Excel 4.0 (XLM) macros by default to block malware",
            "Attackers abuse XLM macros to deliver QakBot and steal crypto wallet keys",
            "Hackers abuse Excel 4.0 macros (XLM) in phishing campaign targeting crypto exchanges",
            "Meta releases XLM-R multilingual model for financial document classification",
            "Stellar Health Expands Provider Network and Value-Based Payment Program",
            "Stellantis Invests in Blockchain Supply-Chain Tracking for Battery Materials",
            "Report revisits NSA's Stellar Wind program and bulk collection of phone network records",
            "Crypto ETFs Record Stellar Inflows as Bitcoin Rallies",
            "Stellar ETF Inflows Lift BlackRock's Bitcoin Fund as Tokenization Demand Grows",
            "Stellar LED Series Delivers 5,000 Lumens for Warehouse Networks",
            "Stellar Data Recovery Launches Ledger Repair Tool for QuickBooks Users",
            "Blockchain Stocks Post a Stellar Week as Stablecoin Bill Advances",
            "XLMedia (AIM: XLM) announces wind-down and return of cash to shareholders",
            "Stellar Bancorp, Inc. Reports Third Quarter 2026 Results",
            "Hackers Target Stellar Cyber Customers in Crypto Phishing Campaign",
            "2026 Was Stellar for Tokenized Treasuries as Assets Top $10 Billion",
            "Crypto Exchange Reports Stellar, Record Quarter as Stablecoin Revenue Soars",
            "Stellar Network Growth at Visa as stablecoin settlement volumes surge",
            "Stellar network effects helped the stablecoin issuer win bank clients",
            "Japanese Soroban Abacus Championship Draws Record Entries",
            "Stellar Partners LLC Acquires Payments Processor to Expand Merchant Network",
            "Stellar Energy Raises Funds for Data Center Cooling as Crypto Miners Pivot to AI",
            "Earnings Remain Stellar for Crypto Brokers Despite Market Slump",
            "Stellar Industries Reports Record Truck Crane Sales; Payments Via Blockchain Pilot Planned",
            "Crypto Broker Shares Rise on Stellar Earnings as Stablecoin Revenue Grows",
            "Bitcoin Miner Returns to Stellar Growth After Tokenization Pivot",
            "Tokenization Startup Partners with Stellar Cyber to Secure Blockchain Nodes",
            "Community Bank Moves Deposits to Stellar Bank Ahead of Stablecoin Launch",
            "Stellar Foundation for the Arts Receives Crypto Donation",
            "Stellar Q3 for Tokenized Funds as BlackRock BUIDL Tops $3 Billion",
            "A Stellar Debut for Circle's IPO as Stablecoin Hype Builds",
            "Galaxy Digital's Stellar Run Continues as Crypto Rebounds",
            "Stellar Capital Management Fined by SEC for Crypto Custody Violations",
            "SEC Charges Stellar Partners Founder in Crypto Ponzi Scheme",
            "Investors Flock to Stellar Crypto Funds as Bitcoin Hits Record",
            "Tokenized Fund Returns Were Stellar in 2026, Report Finds",
            "Tokenized Funds Prove Stellar for Yield Seekers",
            "Moody's Upgrades Stellar Bank Outlook Amid Crypto Lending Push",
            "Crypto Firm Taps Stellar Talent for Tokenization Push",
            "Bitcoin Rally Leads to Stellar Gains for Crypto ETFs",
            "Blockchain Firm Honored for Stellar Customer Service",
            "Tokenization Platform Securitize Hits Stellar Milestone",
            "Researchers find stellar mass black holes; blockchain used to share telescope data",
            "Coinbase: Stellar quarter as stablecoin revenue climbs",
            "Stellar quarter for tokenized treasuries, report says",
            "Excel 4.0 macro (XLM) downloader used to drop crypto-stealing trojan, researchers say",
            "Excel 4.0 macros, also known as XLM, remain a favored lure for crypto wallet stealers",
            "XLM/XL4 macros resurface in phishing campaign targeting crypto traders",
            "Meta AI's XLM-V scales multilingual vocabulary to one million tokens",
            "Researchers fine-tune XLM and mBERT for multilingual crypto sentiment analysis",
            "Trading in XLMedia PLC shares (AIM:XLM) suspended ahead of delisting",
            "XLMedia (XLM.L) share price falls after profit warning",
            "Stablecoin Growth Has Been Nothing Short of Stellar",
            "Simply Stellar: Tokenized Treasury Funds Top $10 Billion",
            "A Stellar, if Volatile, Year for Crypto ETFs",
            "From Good to Stellar: Crypto Exchange Revenue Soars on Stablecoin Fees",
            "Stellar by Any Measure: Tokenized Money Funds Hit Record Assets",
            "Tokenized Treasuries Climb to Stellar Heights as Rates Fall",
            "Crypto Stocks End Quarter on Stellar Note as Stablecoin Bill Passes",
            "Tokenized Fund Issuer on Stellar Streak as Assets Double",
            "Crypto ETF Inflows Remained Stellar for a Third Straight Week",
            "Crypto Lending Still Stellar as Rates Fall, Survey Finds",
            "Crypto Custodian Lays a Stellar Foundation as Tokenization Rules Take Shape",
            "CME Group Reports Stellar Crypto Futures Volume in Third Quarter",
            "Stellar ETF Demand Lifts BlackRock as Crypto Funds Draw $5 Billion",
            "Bitcoin Miners Lead Stellar Blockchain Stock Rally as Crypto Rebounds",
            "Amplify's BLOK Posts Stellar Blockchain ETF Returns in September",
            "Analysts Cheer Stellar Lumen Quarter as AI Fiber Deals Pile Up",
            "Tokenized Fund Inflows Stellar in September as Rates Fall",
            "Verizon Posts Stellar Network Reliability as It Tests Blockchain for Roaming Settlement",
            "Stellar network reliability helps Verizon beat rivals in J.D. Power study",
            "Aave Posts Stellar Protocol Revenue as On-Chain Lending Surges",
            "Hyperliquid Posts Stellar DEX Volume as On-Chain Perps Trading Booms",
            "Crypto IPOs Enjoy Stellar Debuts as Circle and Bullish Soar",
            "A Stellar, Ethereum-Fueled Quarter for Crypto Exchanges",
            "SEC's Stellar Record on Crypto Enforcement Questioned by Lawmakers",
            "Stellar Cyber Adds Crypto Wallet Threat Detection. Stellar's Open XDR platform now monitors blockchain nodes for intrusions.",
            "Stellar Bank Joins Regional Bank Stablecoin Consortium. The Houston lender said Stellar customers will be able to hold USDC.",
            "Crypto Lender Sells Defaulted Loans to Stellar Recovery",
            "Soroban Capital Partners Discloses Stake in Coinbase as Crypto Shares Rally",
            "Soroban Capital Posts Stellar Returns on Energy Bets",
            "Stellar Blade Developer SHIFT UP Explores NFT Tie-In on Blockchain Network",
            "스텔라 블레이드 개발사 시프트업, 가상자산 사업 진출설 부인",
            "스텔란티스, 배터리 공급망에 블록체인 도입",
            "Stellar Cyber adds Stellar network sensors to its Open XDR platform for crypto exchanges",
            "Stellar Health Grows the Stellar Network to 5,000 Primary Care Providers",
            "Tokenized Money Funds Top $12 Billion Stellar demand from treasurers continued in September as assets moved on-chain.",
            "A Stellar, Solana-Style Comeback for Crypto Funds",
            "Stellar Bancorp, Inc. (“Stellar”) completes digital banking upgrade",
            "Investor Optimism and Stellar Guidance Lift Coinbase Shares",
            "Bitcoin and Stellar Jobs Report Lift Markets as Crypto Rallies",
            "Ethereum Posts Stellar, Solana-Beating Quarter",
            # "on Stellar" after a market-move or "build/bet on" verb, "%" or "High".
            "BlackRock Climbs on Stellar Institutional Demand BlackRock said its bitcoin ETF and tokenized BUIDL fund drew record inflows.",
            "Galaxy Digital Rallies on Stellar Mining Revenue Goldman Sachs raised its target on the crypto firm.",
            "Coinbase Stock Jumps on Stellar Institutional Demand for Crypto",
            "Circle Soars on Stellar Fiscal Q2 as USDC Circulation Climbs",
            "Coinbase Gains on Stellar Subscription Revenue From Stablecoin Interest",
            "Robinhood Rises on Stellar Retail Activity in Crypto and Tokenized Stocks",
            "Crypto Miners Rally on Stellar Hashprice as Bitcoin Hits Record",
            "Coinbase Beats on Stellar User Growth as Crypto Trading Rebounds",
            "Coinbase, Circle Soar on Stellar Stablecoin Bill Vote",
            "Tokenization Firms Build on Stellar Investor Demand",
            "Coinbase Capitalizes on Stellar Bitcoin Rally With Record Crypto Volumes",
            "Coinbase Shares Up 9% on Stellar Institutional Demand for Crypto",
            "Crypto Exchange Hits Record High on Stellar Retail Interest in Stablecoins",
            # The predicative adjective in Title Case, after a colon and before a dash.
            "Tokenized Fund Performance Stellar in 2025, Franklin Templeton Says Franklin Templeton said its BENJI tokenized money market fund drew record inflows.",
            "Stablecoin Adoption Stellar on Wall Street, Fed's Waller Says",
            "Circle Debut Stellar as Stablecoin Issuer's Shares Soar",
            "Bullish IPO Stellar as Crypto Listings Heat Up",
            "Crypto Market Sentiment Stellar on Stablecoin Bill Passage",
            "Crypto IPO Market Stellar for Now, Says Galaxy",
            "Robinhood Crypto Revenue Stellar in Q3 as Bitcoin Rallies",
            "Crypto Stocks Stellar as Bitcoin Hits Record",
            "Robinhood Rated Stellar by Analysts After Crypto Revenue Beat",
            "Circle Q2 Earnings: Stellar and Getting Better as USDC Supply Grows",
            "Coinbase Q3 Verdict: Stellar. Crypto Trading Revenue Doubles",
            "Robinhood's crypto revenue: Stellar, analysts say, as bitcoin trading jumps",
            "Grades for the SEC's Crypto Task Force: Stellar on Tokenization, Weak on Custody",
            "Bitcoin Rally Stellar - but Can Crypto Stocks Keep Up?",
            "From Good To Stellar: Crypto Exchange Revenue Soars on Stablecoin Fees",
            # An excerpt that starts with the adjective, after a Title Case title.
            "Coinbase Q3 Earnings Beat Estimates Stellar trading volumes and stablecoin revenue lifted results for the crypto exchange.",
            "Tokenized Treasury Funds Top $10 Billion Stellar institutional inflows continued as assets moved on-chain.",
            "Crypto Exchange Revenue Soars Stellar stablecoin fees lifted the quarter.",
            # "Stellar Partners" the firm, in a charge.
            "SEC Charges Stellar Partners With Fraud in Crypto Ponzi Scheme",
            # Adjective idioms: "Less Than", "Far From", "as Stellar as", "From Stellar to Stalled".
            "BlackRock's Tokenized Fund Returns Less Than Stellar in Q3",
            "JPMorgan's Kinexys Volumes Far From Stellar in First Year on Blockchain",
            "Nasdaq Tokenized Stock Debut Less Than Stellar for Crypto Traders",
            "Fidelity Crypto Fund Flows Not as Stellar as Hoped",
            "Goldman Sachs: Tokenization Returns Less Than Stellar for Banks",
            "CME Group Crypto Futures Volume Less Than Stellar in September",
            "Crypto Treasury Stocks: From Stellar to Stalled",
            "Stellar to Stalled: The Crypto Treasury Company Boom Fades",
            "Tokenized Fund Returns Far From Stellar in 2026, BlackRock Says",
            "Crypto ETF Debut Less Than Stellar for BlackRock",
            "Why Crypto IPOs Have Been Less Than Stellar",
            "Nothing Less Than Stellar: Tokenized Treasury Funds Top $10 Billion",
            "Coinbase Q3 Not as Stellar as Q2 Despite Stablecoin Boost",
            "Circle's First Year: Far from Stellar, but USDC Keeps Growing",
            # Title Case verbs and product nouns outside subject position, noun readings, and
            # result nouns after them.
            "CME Group Sees Stellar Crypto Futures Volume in Third Quarter",
            "NYSE-Listed Crypto Firms Make Stellar Debuts as Tokenization Booms",
            "Two Stellar Launches: BlackRock and Fidelity Tokenized Funds Go Live on Blockchain",
            "Stellar Hits and Misses: What Worked in Tokenization This Year, per Citi",
            "Visa Builds Stellar Ecosystem of Stablecoin Partners",
            "How JPMorgan Built a Stellar Blockchain Team",
            "JPMorgan's Stellar Blockchain Unit Kinexys Hits $2 Billion a Day",
            "Coinbase Sees Stellar Futures Growth as Crypto Derivatives Boom",
            "Kraken's Stellar Futures Business Lifts Crypto Revenue",
            "After Stellar ETF Launch, Solana Eyes New Highs as Crypto Inflows Build",
            "Crypto VC Firm Builds Stellar Network of Founders and Stablecoin Partners",
            "Stellar Foundation Laid for Stablecoin Growth, Says Circle",
            "Tokenized Funds: Stellar Protocol for Growth",
            "Stellar Crypto Futures Volume Lifts CME Group Earnings",
            "Stellar Futures Volumes Help CME Group Beat Estimates as Crypto Rallies",
            "CME Group Q3: Stellar Crypto Futures Volume Lifts Earnings",
            "Stellar Protocol Revenue Lifts Aave as On-Chain Lending Surges",
            "Stellar Network Reliability Helps Verizon Test Blockchain Roaming Settlement",
            "Stellar Launches Lift Crypto IPO Stocks",
            "Stellar Rallies Lift Crypto Stocks",
            "Stellar Gains for Crypto Funds as Bitcoin Rallies",
            # "on Stellar" plus a capitalised word without a deployment verb or a network noun.
            "State Street Profit Tops Forecasts on Stellar Servicing Business; digital asset unit grows",
            "Nasdaq Beats Estimates on Stellar Index Licensing; tokenization push continues",
            "BNY Shares Rising on Stellar Custody Business; tokenization",
            "Robinhood Raises Outlook on Stellar Options Trading as Crypto Revenue Doubles",
            "Coinbase Stock Rising on Stellar Institutional Uptake of Crypto",
            "Galaxy Digital Swings to Profit on Stellar Mining Economics and Crypto Prices",
            "Bitcoin Climbs Back Above $120,000 on Stellar U.S. Jobs Data; crypto stocks follow",
            "Circle Rises on Stellar Surge in USDC Demand",
            "Galaxy Moves to Stellar Profitability as crypto prices rise",
            # Chain lists with the predicative adjective or a result phrase.
            "U.S. Jobs Data Stellar, Bitcoin Slips as Rate-Cut Bets Fade",
            "Payrolls Stellar, Bitcoin Falls",
            "Nvidia Numbers Stellar, Bitcoin Rallies Anyway",
            "Stocks Gain on Bitcoin and Stellar Tech Earnings",
            "Bitcoin and Stellar Retail Trading Lift Robinhood Crypto Revenue",
            "Strong Bitcoin and Stellar Stablecoin Revenue Lift Coinbase",
            # Quoted, bracketed or dash-set adjective.
            'BlackRock\'s Fink: Tokenization Demand Has Been "Stellar"',
            "Analysts Call Coinbase Quarter “Stellar” as Stablecoin Revenue Soars",
            'Circle CEO Calls Q2 "Stellar" as USDC Supply Grows',
            "Circle Q2 Earnings — Stellar and Getting Better as USDC Supply Grows",
            "Coinbase Q3 Verdict - Stellar. Crypto Trading Revenue Doubles",
            "Robinhood Crypto Revenue (Stellar) Lifts Shares as Bitcoin Rallies",
            # Other Stellar companies named in title and excerpt.
            "SEC Charges Stellar Partners Founder in Crypto Ponzi Scheme The complaint alleges Stellar's founder promised investors crypto returns.",
            "SEC Charges Stellar Capital Management for Crypto Custody Violations The SEC alleges that Stellar Capital Management LLC (“Stellar”) failed to safeguard client crypto assets.",
            "Stellar Energy Wins Data Center Cooling Contract Stellar's modular cooling units serve bitcoin mining sites and blockchain data centers.",
            "Stellar Industries Adds Crane Financing Stellar's truck cranes can now be bought with on-chain financing.",
        ],
    },
}

NEW_PROJECTS = {"hyperliquid": "HYPE", "dogecoin": "DOGE", "monero": "XMR",
                "whitebit": "WBT", "cardano": "ADA", "rain": "RAIN"}
CHANGED_PROJECTS = {"chainlink": "LINK", "stellar": "XLM"}


def _params(kind: str) -> list:
    return [pytest.param(eid, text, id=f"{eid}-{kind}-{i:02d}")
            for eid, case in CASES.items() for i, text in enumerate(case[kind])]


@pytest.fixture(scope="module")
def all_entities():
    return load_entities(ROOT / "config" / "entities.yaml")


def matched_ids(text, entities) -> list[str]:
    return [m.entity_id for m in match_text(text, entities)]


def test_case_lists_have_no_duplicates_or_overlap():
    for eid, case in CASES.items():
        assert len(set(case["pos"])) == len(case["pos"]), eid
        assert len(set(case["neg"])) == len(case["neg"]), eid
        assert not set(case["pos"]) & set(case["neg"]), eid


def test_rank_entities_are_uncontrolled_projects(all_entities):
    by_id = {e.id: e for e in all_entities}
    for eid, token in {**NEW_PROJECTS, **CHANGED_PROJECTS}.items():
        entity = by_id[eid]
        assert entity.kind == "project"
        assert entity.tokens == (token,)
        assert entity.rules
    for eid in NEW_PROJECTS:
        # Coverage, not the Q7 interest sample or control group.
        assert not by_id[eid].control


@pytest.mark.parametrize("entity_id, text", _params("pos"))
def test_positive_matches_its_entity(entity_id, text, all_entities):
    assert entity_id in matched_ids(text, all_entities)


@pytest.mark.parametrize("entity_id, text", _params("neg"))
def test_negative_does_not_match_the_entity(entity_id, text, all_entities):
    assert entity_id not in matched_ids(text, all_entities)


def test_upbit_prices_only_same_asset_krw_listings():
    market = load_market_config(ROOT / "config" / "market.yaml")
    for symbol in ("LINK", "XLM", "DOGE", "ADA"):
        assert market.venue_for(symbol).name == "upbit", symbol
    # No Upbit KRW market for the same asset: reactions are recorded as no_market.
    for symbol in ("HYPE", "XMR", "WBT", "RAIN"):
        assert market.venue_for(symbol) is None, symbol
